---
title: "Exploring 2016 San Diego Police Stop Data"
output:
  html_document: default
  html_notebook: default
---

```{r}
require(tidyverse)
require(knitr)
```

```{r}
race <- read_csv("p_stop_data/vehicle_stops_race_codes.csv")
```

```{r}
stops <- read_csv("p_stop_data/vehicle_stops_2016_datasd.csv")
```

```{r}
details <- read_csv("p_stop_data/vehicle_stops_search_details_2016_datasd.csv")
```

```{r}
dict <- read_csv("p_stop_data/vehicle_stops_dictionary.csv")
```

The research paper notes that in 2014 there were 144164 traffic stops and in 2015 there were 115405 traffic stops. In 2016 there were `r nrow(stops)` stops. Here are the percentage of each variable that were NA: 

```{r}
missing <- tibble(
  stop_description = c(
    "driver_race", 
    "driver_age", 
    "driver_gender", 
    "residency_status", 
    "service_area", 
    "stop_cause", 
    "stop_time", 
    "stop_date", 
    "arrested", 
    "searched", 
    "obtained_consent", 
    "contraband_found", 
    "property_seized"
  ), 
  perc_missing = c(
    mean(is.na(stops$subject_race)), 
    mean(is.na(stops$subject_age)), 
    mean(is.na(stops$subject_sex)), 
    mean(is.na(stops$sd_resident)), 
    mean(is.na(stops$service_area)), 
    mean(is.na(stops$stop_cause)), 
    mean(is.na(stops$stop_time)), 
    mean(is.na(stops$stop_date)), 
    mean(is.na(stops$arrested)), 
    mean(is.na(stops$searched)), 
    mean(is.na(stops$obtained_consent)), 
    mean(is.na(stops$contraband_found)), 
    mean(is.na(stops$property_seized))
  )
) 

missing <- missing %>% 
  mutate(perc_missing = round(perc_missing * 100, 2))

kable(missing)
```